# Generated by Django 6.0 on 2025-12-14 07:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200)),
                ('content', tinymce.models.HTMLField(help_text='Content of blog post')),
                ('image', models.ImageField(blank=True, help_text='Blog post image', upload_to='blog/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('comments_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of comments')),
                ('share_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of share')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled')], default='draft', help_text='Status on the blog post', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name,e.g. , Technology', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the comment', max_length=100)),
                ('email', models.EmailField(help_text='Email of the comment', max_length=254)),
                ('message', tinymce.models.HTMLField(help_text='Message of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag Name,e.g. , Technology', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
